import { Task, User } from './types'

export const mockUsers: User[] = [
  {
    id: 'u1',
    name: 'Sarah Connor',
    email: 'sarah@example.com',
    role: 'Manager',
    programme: 'Alpha',
  },
  {
    id: 'u2',
    name: 'John Smith',
    email: 'john@example.com',
    role: 'Contributor',
    programme: 'Alpha',
  },
  {
    id: 'u3',
    name: 'Elena Rodriguez',
    email: 'elena@example.com',
    role: 'Head',
    programme: 'Beta',
  },
]

export const mockTasks: Task[] = [
  {
    id: 'A-00001',
    title: 'Q3 Financial Review',
    activityName: 'Q3 Financial Review',
    purpose: 'Quarterly financial compliance',
    endDate: '2026-07-15',
    costCenterId: 'CC-100',
    budgetLineId: 'BL-200',
    workorderId: 'WO-300',
    accountId: 'ACC-400',
    comments: 'Requires attention from SPM',
    description: 'Quarterly review of budget vs actuals for Programme Alpha.',
    status: 'In Progress',
    category: 'Finance',
    location: 'New York',
    projectOwnerId: 'u1',
    assigneeId: 'u2',
    startDate: '2026-07-01',
    dueDate: '2026-07-15',
    programme: 'Alpha',
    project: 'PRJ-Fin',
    type: 'Review',
    priority: 'High',
    costEstimated: 5000,
    inBudget: true,
    history: [
      { id: 'h1', timestamp: '2026-06-28T10:00:00Z', userId: 'u1', action: 'Created task' },
      {
        id: 'h2',
        timestamp: '2026-07-02T14:30:00Z',
        userId: 'u2',
        action: 'Status changed to In Progress',
      },
    ],
  },
  {
    id: 'A-00002',
    title: 'Annual Staff Retreat',
    activityName: 'Annual Staff Retreat',
    endDate: '2026-08-12',
    description: 'Organize the annual offsite for team building.',
    status: 'To Do',
    category: 'HR',
    location: 'Geneva',
    projectOwnerId: 'u3',
    assigneeId: 'u1',
    startDate: '2026-08-10',
    dueDate: '2026-08-12',
    programme: 'Beta',
    project: 'PRJ-HR',
    type: 'Event',
    priority: 'Medium',
    costEstimated: 25000,
    inBudget: true,
    history: [
      { id: 'h3', timestamp: '2026-06-15T09:15:00Z', userId: 'u3', action: 'Created task' },
    ],
  },
  {
    id: 'A-00003',
    title: 'Vendor Contract Renewal',
    activityName: 'Vendor Contract Renewal',
    endDate: '2026-06-01',
    description: 'Renew IT services contract with TechCorp.',
    status: 'Past Due',
    category: 'Procurement',
    location: 'London',
    projectOwnerId: 'u1',
    assigneeId: 'u2',
    startDate: '2026-05-01',
    dueDate: '2026-06-01',
    programme: 'Alpha',
    project: 'PRJ-IT',
    type: 'Legal',
    priority: 'Urgent',
    costEstimated: 120000,
    inBudget: false,
    history: [
      { id: 'h4', timestamp: '2026-05-01T11:00:00Z', userId: 'u1', action: 'Created task' },
    ],
  },
  {
    id: 'A-00004',
    title: 'Website Redesign',
    activityName: 'Website Redesign',
    endDate: '2026-04-20',
    description: 'Overhaul corporate site for accessibility.',
    status: 'Done',
    category: 'IT',
    location: 'Remote',
    projectOwnerId: 'u3',
    assigneeId: 'u2',
    startDate: '2026-01-10',
    dueDate: '2026-04-20',
    programme: 'Beta',
    project: 'PRJ-IT',
    type: 'Project',
    priority: 'High',
    costEstimated: 45000,
    inBudget: true,
    history: [
      {
        id: 'h5',
        timestamp: '2026-04-20T16:45:00Z',
        userId: 'u2',
        action: 'Status changed to Done',
      },
    ],
  },
]
