DO $$
BEGIN
  ALTER TABLE public.activities
    ADD COLUMN IF NOT EXISTS event_location TEXT,
    ADD COLUMN IF NOT EXISTS event_participants_count INTEGER,
    ADD COLUMN IF NOT EXISTS event_date_status TEXT,
    ADD COLUMN IF NOT EXISTS event_location_status TEXT,
    ADD COLUMN IF NOT EXISTS event_include_calendar BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS event_links TEXT,
    ADD COLUMN IF NOT EXISTS event_can_change_time BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS event_change_time_desc TEXT,
    ADD COLUMN IF NOT EXISTS event_comments TEXT,
    ADD COLUMN IF NOT EXISTS inv_ems BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS inv_ems_comments TEXT,
    ADD COLUMN IF NOT EXISTS inv_protocol BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS inv_sg BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS inv_cop_bod BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS inv_cop_bod_role TEXT,
    ADD COLUMN IF NOT EXISTS inv_heads BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS inv_heads_role TEXT,
    ADD COLUMN IF NOT EXISTS inv_commd BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS inv_commd_role TEXT,
    ADD COLUMN IF NOT EXISTS inv_staff BOOLEAN DEFAULT false,
    ADD COLUMN IF NOT EXISTS inv_staff_involvement TEXT,
    ADD COLUMN IF NOT EXISTS inv_kaiciid_delegation TEXT,
    ADD COLUMN IF NOT EXISTS inv_travel_days TEXT,
    ADD COLUMN IF NOT EXISTS inv_orgs_involved TEXT,
    ADD COLUMN IF NOT EXISTS inv_orgs_desc TEXT,
    ADD COLUMN IF NOT EXISTS inv_participants_type TEXT,
    ADD COLUMN IF NOT EXISTS inv_individuals_meet TEXT,
    ADD COLUMN IF NOT EXISTS rbm_outcomes TEXT,
    ADD COLUMN IF NOT EXISTS rbm_outputs TEXT,
    ADD COLUMN IF NOT EXISTS sg_role TEXT,
    ADD COLUMN IF NOT EXISTS sg_speaking_notes TEXT;
END $$;
